name: Build and Publish NuGet Package

on:
  push:
    tags:
      - 'v*.*.*'   # Solo tags semánticos tipo v1.2.3


#permiso necesarios para escribir en el nuget de github
permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify tag is on main
        run: |
          git fetch origin main
          # Compara el commit del tag con el de main
          TAG_COMMIT=$(git rev-parse $GITHUB_REF)
          MAIN_COMMIT=$(git rev-parse origin/main)
          if [ "$TAG_COMMIT" != "$MAIN_COMMIT" ]; then
            echo "Tag must be created from main!"
            exit 1
          fi

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore src/jim.mddr/jim.mddr.csproj

      - name: Build
        run: dotnet build src/jim.mddr/jim.mddr.csproj --configuration Release --no-restore

      - name: Pack NuGet package
        run: |
          dotnet pack src/jim.mddr/jim.mddr.csproj --configuration Release --no-build -o ./artifacts /p:PackageVersion=${GITHUB_REF_NAME#v} 

      - name: Publish to GitHub Packages
        run: |
          dotnet nuget push "./artifacts/*.nupkg" \
          --api-key ${{ secrets.GITHUB_TOKEN }} \
          --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
