name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main        # Solo en la rama main
    tags:
      - 'v*.*.*'    # Solo cuando se pushea un tag del estilo v1.0.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.0'

      - name: Restore dependencies
        run: dotnet restore src/jim.mddr/jim.mddr.csproj

      - name: Build solution
        run: dotnet build src/jim.mddr/jim.mddr.csproj --configuration Release --no-restore

      - name: Run tests
        run: dotnet test src/jim.mddr/jim.mddr.csproj --configuration Release --no-build --verbosity normal

      - name: Pack NuGet package
        run: dotnet pack src/jim.mddr/jim.mddr.csproj --configuration Release --no-build -o ./artifacts /p:PackageVersion=${GITHUB_REF#refs/tags/v}

      - name: Add GitHub NuGet source
        run: dotnet nuget add source \
          --username ${{ github.actor }} \
          --password ${{ secrets.GITHUB_TOKEN }} \
          --store-password-in-clear-text \
          --name github \
          "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
